-- Generated by Mocodo 4.2.12

CREATE TABLE Appartenir (
  PRIMARY KEY (code_quiz, code_theme),
  code_quiz  VARCHAR(42) NOT NULL,
  code_theme VARCHAR(42) NOT NULL
);

CREATE TABLE NIVEAU (
  PRIMARY KEY (code_niveau),
  code_niveau VARCHAR(42) NOT NULL,
  nom         VARCHAR(42)
);

CREATE TABLE QUESTION (
  PRIMARY KEY (code_question),
  code_question VARCHAR(42) NOT NULL,
  titre         VARCHAR(42),
  wiki          VARCHAR(42),
  anecdote      VARCHAR(42),
  code_quiz     VARCHAR(42) NOT NULL,
  code_niveau   VARCHAR(42) NOT NULL
);

CREATE TABLE QUIZ (
  PRIMARY KEY (code_quiz),
  code_quiz        VARCHAR(42) NOT NULL,
  titre            VARCHAR(42),
  description      VARCHAR(42),
  code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE REPONSE (
  PRIMARY KEY (code_reponse),
  code_reponse  VARCHAR(42) NOT NULL,
  description   VARCHAR(42),
  est_valide    VARCHAR(42),
  code_question VARCHAR(42) NOT NULL
);

CREATE TABLE THEME (
  PRIMARY KEY (code_theme),
  code_theme VARCHAR(42) NOT NULL,
  nom        VARCHAR(42)
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (code_utilisateur),
  code_utilisateur VARCHAR(42) NOT NULL,
  email            VARCHAR(42),
  prenom           VARCHAR(42),
  nom              VARCHAR(42),
  mot_de_passe     VARCHAR(42)
);

ALTER TABLE Appartenir ADD FOREIGN KEY (code_theme) REFERENCES THEME (code_theme);
ALTER TABLE Appartenir ADD FOREIGN KEY (code_quiz) REFERENCES QUIZ (code_quiz);

ALTER TABLE QUESTION ADD FOREIGN KEY (code_niveau) REFERENCES NIVEAU (code_niveau);
ALTER TABLE QUESTION ADD FOREIGN KEY (code_quiz) REFERENCES QUIZ (code_quiz);

ALTER TABLE QUIZ ADD FOREIGN KEY (code_utilisateur) REFERENCES UTILISATEUR (code_utilisateur);

ALTER TABLE REPONSE ADD FOREIGN KEY (code_question) REFERENCES QUESTION (code_question);
